In [2]:
import tensorflow as tf

In [2]:
"tf version:", tf.__version__
"tf run mode:", tf.executing_eagerly()
tf.config.list_physical_devices()
#tf.config.list_physical_devices("CPU")
#tf.config.list_physical_devices("GPU")
tf.test.is_gpu_available()
tf.test.gpu_device_name()
from tensorflow.python.client import device_lib
local_devices = device_lib.list_local_devices()
local_devices
# 使用 GPU 时，建议加入：
gpu_physical_devices = tf.config.experimental.list_physical_devices('GPU')
gpu_physical_devices
# 设置 gpu 的内存是增长型使用
tf.config.experimental.set_memory_growth(gpu_physical_devices[0], True)

('tf version:', '2.9.1')

('tf run mode:', True)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

'/device:GPU:0'

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 9742389359850503999
 xla_global_id: -1,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 4919132160
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 6603132053019617892
 physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 970M, pci bus id: 0000:01:00.0, compute capability: 5.2"
 xla_global_id: 416903419]

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
# 查看张量的值
t0 = tf.constant([[1, 2], [3, 4]])  # list 的常量
t0 
t0.numpy()
type(t0)
type(t0.numpy())

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

array([[1, 2],
       [3, 4]])

tensorflow.python.framework.ops.EagerTensor

numpy.ndarray

In [4]:
# 01:基于 python list 列表创建张量
pl = [[1, 2], [3, 4]]
t1 = tf.constant(pl)
"t1:", t1
"t1 value:", t1.numpy()
"t1 type:", type(t1)
"t1 value type:", type(t1.numpy())

('t1:',
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>)

('t1 value:',
 array([[1, 2],
        [3, 4]]))

('t1 type:', tensorflow.python.framework.ops.EagerTensor)

('t1 value type:', numpy.ndarray)

In [5]:
# 02:基于 numpy.ndarray 数组创建张量
import numpy as np
# 整型数组
t2 = tf.constant(np.array([1, 2]))
"t2:", t2
"t2 value:", t2.numpy()
"t2 type:", type(t2)
"t2 value type:", type(t2.numpy())
# 浮点型数组 - 默认 float64
t2_2 = tf.constant(np.array([1., 2.0]))
"t2_2:", t2_2
"t2_2 value:", t2_2.numpy()
"t2_2 type:", type(t2_2)
"t2_2 value type:", type(t2_2.numpy())
# 浮点型数组 - 显示指定为 float32
t2_3 = tf.constant(np.array([1., 2.0]), dtype=tf.float32)
"t2_3:", t2_3
"t2_3 value:", t2_3.numpy()
"t2_3 type:", type(t2_3)
"t2_3 value type:", type(t2_3.numpy())

('t2:', <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>)

('t2 value:', array([1, 2]))

('t2 type:', tensorflow.python.framework.ops.EagerTensor)

('t2 value type:', numpy.ndarray)

('t2_2:', <tf.Tensor: shape=(2,), dtype=float64, numpy=array([1., 2.])>)

('t2_2 value:', array([1., 2.]))

('t2_2 type:', tensorflow.python.framework.ops.EagerTensor)

('t2_2 value type:', numpy.ndarray)

('t2_3:',
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>)

('t2_3 value:', array([1., 2.], dtype=float32))

('t2_3 type:', tensorflow.python.framework.ops.EagerTensor)

('t2_3 value type:', numpy.ndarray)

In [6]:
# 03:基于 数字（单一数值）创建张量
t3 = tf.constant(1)
"t3:", t3
"t3.numpy():", t3.numpy()
"t3 type:", type(t3)
"t3 value type", type(t3.numpy())
t3_2 = tf.constant(2.)
"t3_2:", t3_2
"t3_2.numpy():", t3_2.numpy()
"t3_2 type:", type(t3_2)
"t3_2 value type", type(t3_2.numpy())
# 显示指定元素类型
# 建议： 多个参数时，最好给出：参数的名称=参数值
#t3_3 = tf.constant(2., dtype=tf.float64)
t3_3 = tf.constant(value = 2., dtype=tf.float64)
t3_3

('t3:', <tf.Tensor: shape=(), dtype=int32, numpy=1>)

('t3.numpy():', 1)

('t3 type:', tensorflow.python.framework.ops.EagerTensor)

('t3 value type', numpy.int32)

('t3_2:', <tf.Tensor: shape=(), dtype=float32, numpy=2.0>)

('t3_2.numpy():', 2.0)

('t3_2 type:', tensorflow.python.framework.ops.EagerTensor)

('t3_2 value type', numpy.float32)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [7]:
# 04:基于 布尔值 创建张量
t4 = tf.constant([True, False])
"t4:", t4
"t4.numpy():", t4.numpy()
"t4 type:", type(t4)
"t4 value type", type(t4.numpy())
# True => 1/1.  False => 0/0.
tf.cast(t4, tf.int32)
tf.cast(t4, tf.float32)
# 非0 => True  0 => False
tmp = tf.constant([-1, 0, 1, 2.0])
tf.cast(tmp, tf.bool)

('t4:', <tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>)

('t4.numpy():', array([ True, False]))

('t4 type:', tensorflow.python.framework.ops.EagerTensor)

('t4 value type', numpy.ndarray)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 0.], dtype=float32)>

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [8]:
# 05:基于 字符串 创建张量
t5 = tf.constant("hello")
"t5:", t5
# Python 字符（串）以 unicode 编码表达
# Tensorflow 字符（串） 以字节数组的形式表达
# numpy=b'hello'
"t5.numpy():", t5.numpy()
"t5 type:", type(t5)
# bytes  == 字节数组
"t5 value type", type(t5.numpy())
# unicode === ascii == utf8
# english -- ascii == 1byte
# 比如：中文字符-2个字节 == 2byte表示一个字符，
# 此时，需要3个字节表示需要两个字节表述的中文字符，
# utf8 中，规定：第1个字节 最高位111.。。 后2个字节表示实际的字符编码
# 在 tf 中 中文字符占 3 个字节
tf.constant("天下")

('t5:', <tf.Tensor: shape=(), dtype=string, numpy=b'hello'>)

('t5.numpy():', b'hello')

('t5 type:', tensorflow.python.framework.ops.EagerTensor)

('t5 value type', bytes)

<tf.Tensor: shape=(), dtype=string, numpy=b'\xe5\xa4\xa9\xe4\xb8\x8b'>

In [9]:
# 06:tf.convert_to_tensor()方法将现有数据转换为张量
import numpy as np
na = np.arange(12).reshape(3, 4)
na
type(na)
# 完成转换
ta = tf.convert_to_tensor(na)
"ta:", ta
"ta.numpy():", ta.numpy()
"ta type:", type(ta)
"ta value type", type(ta.numpy())
string_array = ["hello", "天下"]
t_strings = tf.constant(string_array)
t_strings.numpy()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

numpy.ndarray

('ta:',
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>)

('ta.numpy():',
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

('ta type:', tensorflow.python.framework.ops.EagerTensor)

('ta value type', numpy.ndarray)

array([b'hello', b'\xe5\xa4\xa9\xe4\xb8\x8b'], dtype=object)

In [10]:
# 07:各种特殊张量
# 全0张量
tf.zeros(shape=(6))
tf.zeros(shape=[2, 3])
# 全1张量
tf.ones(shape=(6))
tf.ones(shape=[2, 3])
# like 。。
tf.zeros_like(tf.ones(shape=[2, 3]))
# 同值张量
tf.fill([2, 3], 9)
tf.fill([2, 3], 9.)
tf.fill([2,], "hello")
tf.fill([], True)
# 正态分布
tf.random.normal([2, 3])
tf.random.normal(shape=[2, 3, 4], mean=0.0, stddev=2.0)
# 截断正态分布
tf.random.truncated_normal(shape=[2, 3, 4], mean=0.0, stddev=2.0)
# 均匀分布
tf.random.set_seed(42)  # 每次生成的随机数据一致
tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype='int32')
tf.random.set_seed(42)  # 每次生成的随机数据一致
tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype='int32')
# 没有起作用。
#tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype='int32', seed=42)
#tf.random.uniform(shape=(3, 3), minval=1, maxval=10, dtype='int32', seed=42)
# 序列张量,前闭后开空间
tf.range(10)
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[9., 9., 9.],
       [9., 9., 9.]], dtype=float32)>

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'hello'], dtype=object)>

<tf.Tensor: shape=(), dtype=bool, numpy=True>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.3258864 , -1.3374125 , -1.6455876 ],
       [ 0.4674322 , -1.0085659 , -0.49727106]], dtype=float32)>

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-3.0900676 ,  0.06106665, -1.2160052 ,  3.9257355 ],
        [ 0.44119656,  3.898708  ,  0.4625773 , -1.0210679 ],
        [ 1.8632311 , -2.8251648 , -1.0558579 , -3.9115715 ]],

       [[-0.34709856,  1.4259995 ,  0.54207313, -0.9045479 ],
        [ 3.4186418 , -1.6602695 ,  3.3084226 ,  1.4107931 ],
        [ 0.507739  ,  1.5735748 , -0.255079  , -1.8297805 ]]],
      dtype=float32)>

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 1.9810729 ,  1.1371591 , -0.5367684 , -1.5745926 ],
        [-1.1894002 ,  0.61738336, -1.8490044 , -2.714796  ],
        [-0.855381  , -1.9755341 ,  3.5090632 ,  0.40457392]],

       [[-1.9589148 ,  0.31488922, -0.6768407 , -3.8647504 ],
        [-0.14740387,  3.41704   ,  0.8433062 ,  1.695899  ],
        [-0.07205007, -2.1923492 ,  2.2899547 , -0.191505  ]]],
      dtype=float32)>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 6, 9],
       [4, 8, 3],
       [8, 8, 8]])>

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 6, 9],
       [4, 8, 3],
       [8, 8, 8]])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [11]:
tf.fill(dims=[2, 3], value=9)
# tf.constant(value=9, shape=[2,3])
tf.constant(shape=[2,3], value=9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [12]:
# 关于变量
ct = tf.constant([-1, 0, 1, 2])
# 转换为变量类型
vt = tf.Variable(ct)
vt
vt.name, vt.trainable
v = tf.Variable(1.)
v.assign(2.)
v.assign_add(0.5)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-1,  0,  1,  2])>

('Variable:0', True)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.5>

In [4]:
# 获取张量的类型
t = tf.constant(3.1)
type(t)
tf.is_tensor(t)

tensorflow.python.framework.ops.EagerTensor

True

In [6]:
type(t.numpy())

numpy.float32

In [7]:
t =  tf.constant([[1,2], [3, 4]])
type(t)
t.numpy()
type(t.numpy())

tensorflow.python.framework.ops.EagerTensor

array([[1, 2],
       [3, 4]])

numpy.ndarray

In [16]:
import numpy as np
np.pi
# 默认会转换为 tf.float32 
t_pi_float32 = tf.constant(np.pi, dtype=tf.float32)
t_pi_float32
t_pi_float64 = tf.constant(np.pi, dtype=tf.float64)
t_pi_float64
# t_pi_float64.numpy().dtypes
# dtypes(t_pi_float64)

3.141592653589793

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

NameError: name 'dtypes' is not defined

In [20]:
# 上溢
c = tf.constant(123456789, dtype=tf.int32)
c
type(c)
c.dtype
d = tf.cast(c, tf.int16)
d

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

tensorflow.python.framework.ops.EagerTensor

tf.int32

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [22]:
b = tf.constant([True, False])
tf.cast(b, tf.int32)
v = tf.constant([-1, 0, 1, 2.0])
tf.cast(v, tf.bool)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [23]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
x.ndim
x.shape
x.dtype

2

TensorShape([3, 2])

tf.int32

In [24]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [25]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
tf.random.shuffle(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]])>

In [27]:
tf.random.shuffle(v)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  2., -1.,  0.], dtype=float32)>

In [28]:
image_rgb = tf.random.uniform([28, 28, 3], maxval=255, dtype=tf.int32)
image_rgb
image_rgbs = tf.random.uniform([10, 28, 28, 3], maxval=255, dtype=tf.int32)
image_rgbs

<tf.Tensor: shape=(28, 28, 3), dtype=int32, numpy=
array([[[ 69, 233, 142],
        [156, 114, 107],
        [181, 185,  87],
        ...,
        [ 62,  58, 135],
        [115,  66, 230],
        [170,  13,  64]],

       [[135, 109,   2],
        [ 35, 122,  55],
        [167, 228, 109],
        ...,
        [200, 185,  98],
        [ 36,  40, 158],
        [167,  35, 207]],

       [[209, 107,  63],
        [233, 165, 131],
        [215,  83, 183],
        ...,
        [ 52, 100, 160],
        [215,  55,  12],
        [  2, 172, 118]],

       ...,

       [[148,  33, 181],
        [  2, 146, 136],
        [ 43, 237, 147],
        ...,
        [115, 202,  90],
        [ 14,  50,   7],
        [221,  36,  39]],

       [[204,  43, 218],
        [ 76, 244,  94],
        [197, 198, 211],
        ...,
        [228, 143,  52],
        [145, 224, 156],
        [ 24, 235,  24]],

       [[229, 141, 151],
        [ 41, 174, 182],
        [183,  34, 237],
        ...,
        [ 99,  25,  30]

<tf.Tensor: shape=(10, 28, 28, 3), dtype=int32, numpy=
array([[[[  4, 156,  79],
         [ 73, 190,  26],
         [178,  82,  56],
         ...,
         [ 92, 175,  81],
         [174,   4, 196],
         [143,  93,  73]],

        [[ 64, 207, 130],
         [177,  39,  37],
         [186, 186, 148],
         ...,
         [244,  92, 192],
         [149, 119, 149],
         [ 28,  91,  69]],

        [[ 10, 231, 155],
         [189, 132, 116],
         [203, 186,  44],
         ...,
         [153, 156, 234],
         [ 35, 214,  56],
         [105, 120, 247]],

        ...,

        [[211,  78, 149],
         [228,   4, 161],
         [186, 148, 228],
         ...,
         [172, 153,  90],
         [ 30,  30,  85],
         [ 30, 116, 225]],

        [[ 65,  71,  52],
         [221, 143, 143],
         [160, 178, 144],
         ...,
         [168, 165, 161],
         [156,  97,  95],
         [ 22, 197, 116]],

        [[ 93, 132, 153],
         [199, 130,  95],
         [104, 155,

In [36]:
a = tf.range(24)
a
b = tf.reshape(a, [2, 3, 4])
b
c = tf.reshape(a, [3, 2, 4])
c
d = tf.reshape(a, (4, 6))
d
e = tf.reshape(a, (2, -1, 4))
e

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])>

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])>

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [42]:
t = tf.constant([1, 2, 3])
t.ndim, t.shape, t.numpy
t2 = tf.expand_dims(t, 0)
t2.ndim, t2.shape, t2.numpy()
t1 = tf.expand_dims(t, 1)
t1.ndim, t1.shape, t1.numpy()

(1,
 TensorShape([3]),
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>>)

(2, TensorShape([1, 3]), array([[1, 2, 3]]))

(2,
 TensorShape([3, 1]),
 array([[1],
        [2],
        [3]]))

In [43]:
a = tf.range(24)
b = tf.reshape(a, [2, 3, 4])
b.ndim, b.shape, b.numpy()
b0 = tf.expand_dims(b, 0)
"b0: ", b0.ndim, b0.shape, b0.numpy()
b1 = tf.expand_dims(b, 1)
"b1: ", b1.ndim, b1.shape, b1.numpy()
b2 = tf.expand_dims(b, 2)
"b2: ", b2.ndim, b2.shape, b2.numpy()
b3 = tf.expand_dims(b, 3)
"b3: ", b3.ndim, b3.shape, b3.numpy()

(3,
 TensorShape([2, 3, 4]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

('b0: ',
 4,
 TensorShape([1, 2, 3, 4]),
 array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]]))

('b1: ',
 4,
 TensorShape([2, 1, 3, 4]),
 array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]],
 
 
        [[[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]]))

('b2: ',
 4,
 TensorShape([2, 3, 1, 4]),
 array([[[[ 0,  1,  2,  3]],
 
         [[ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11]]],
 
 
        [[[12, 13, 14, 15]],
 
         [[16, 17, 18, 19]],
 
         [[20, 21, 22, 23]]]]))

('b3: ',
 4,
 TensorShape([2, 3, 4, 1]),
 array([[[[ 0],
          [ 1],
          [ 2],
          [ 3]],
 
         [[ 4],
          [ 5],
          [ 6],
          [ 7]],
 
         [[ 8],
          [ 9],
          [10],
          [11]]],
 
 
        [[[12],
          [13],
          [14],
          [15]],
 
         [[16],
          [17],
          [18],
          [19]],
 
         [[20],
          [21],
          [22],
          [23]]]]))

In [46]:
"b3: ", b3.ndim, b3.shape, b3.numpy()
# b31 = tf.squeeze(b3, 1)
b31 = tf.squeeze(b3)
"b31: ", b31.ndim, b31.shape, b31.numpy()

('b3: ',
 4,
 TensorShape([2, 3, 4, 1]),
 array([[[[ 0],
          [ 1],
          [ 2],
          [ 3]],
 
         [[ 4],
          [ 5],
          [ 6],
          [ 7]],
 
         [[ 8],
          [ 9],
          [10],
          [11]]],
 
 
        [[[12],
          [13],
          [14],
          [15]],
 
         [[16],
          [17],
          [18],
          [19]],
 
         [[20],
          [21],
          [22],
          [23]]]]))

('b31: ',
 3,
 TensorShape([2, 3, 4]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [53]:
image = tf.random.uniform([28, 28], maxval=255, dtype=tf.int32)
image_red_channel = tf.expand_dims(image, axis=2)
image_red_channel.ndim, image_red_channel.shape
image_green_channel = tf.expand_dims(image, axis=2)
image_green_channel.ndim, image_green_channel.shape
image_blue_channel = tf.expand_dims(image, axis=2)
image_blue_channel.ndim, image_blue_channel.shape
image_rgb = tf.concat([image_red_channel, image_green_channel, image_blue_channel], axis = 2)
# 将image_rgb一张图片放入样本集中？
image_rgb_set = tf.expand_dims(image_rgb, 0)
image_rgb_set.shape
image_rgb.ndim, image_rgb.shape
image_red, image_green, image_blue = tf.split(image_rgb, 3, axis=2)

(3, TensorShape([28, 28, 1]))

(3, TensorShape([28, 28, 1]))

(3, TensorShape([28, 28, 1]))

TensorShape([1, 28, 28, 3])

(3, TensorShape([28, 28, 3]))

In [56]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z1 = tf.stack((x, y), axis=0)
z1.ndim, z1.shape, z1.numpy()
z2 = tf.stack((x, y), axis=1)
z2.ndim, z2.shape, z2.numpy()

(2,
 TensorShape([2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

(2,
 TensorShape([3, 2]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))